services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'    

    